version: '3.1'

services:
  wp:
    build: .
    restart: always
    environment:
      WORDPRESS_DB_HOST: dbhost
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wpname
    volumes:
      - ./wp-content/plugins:/var/www/html/wp-content/plugins:z
      - ./wp-content/themes:/var/www/html/wp-content/themes:z
    ports:
      - 80:80
